version: '3'
services: 
    database:
        image: "postgres"
        container_name: "wb-app-database"
        env_file:
        - database.env
        volumes:
        - database-data:/var/lib/postgresql/data/
    backend:
        build: ./backend/
        ports:
        - "3001:3001"
        volumes:
        - ./backend:/usr/src/app
        depends_on:
        - database
volumes: 
    database-data: